name: eql_cmx_portal_cicd_transport_portal_data_pipeline_to_sit_env.yml

on:
  workflow_call :
    inputs:
        portal_name:
          description: 'name of the portal'
          required: true
          type: string
    secrets:
      build_url:
        description: 'portal_data environment url.'
        required: true      
      build_client_id:
        description: 'The portal_data client id'
        required: true
      build_secrets_id:
        description: 'The secret value for authentication for portal_data'
        required: true
      build_tenant_id:
        description: 'The tenant id'
        required: true
      sit_url:
        description: 'portal_data environment url.'
        required: true      
      sit_client_id:
        description: 'The portal_data client id'
        required: true
      sit_secrets_id:
        description: 'The secret value for authentication for portal_data'
        required: true
      sit_tenant_id: 
        description: 'The tenant id'
        required: true
      website_id:
        description: 'The website id'
        required: true
        

jobs:
  download-portal-data-from-build-env:
    runs-on:  ubuntu-latest
    environment: build
    env:
      RUNNER_DEBUG: 1
    steps:

    - uses: actions/checkout@v3
      with:
        lfs: true
        
    - name: download-paportal
      uses: microsoft/powerplatform-actions/download-paportal@v0
      with:
        environment-url: ${{ secrets.build_url }}
        app-id: ${{ secrets.build_client_id }}
        client-secret: ${{ secrets.build_secrets_id }}
        tenant-id: ${{ secrets.build_tenant_id }}
        download-path: portaldata
        website-id:  ${{ secrets.website_id }} 
        overwrite: true

    - name: Upload the ready to ship portal-data to GH artifact store
      uses: actions/upload-artifact@v2
      with:
        name: build-portaldata
        path: portaldata/rdm-electrical-contractors-portal
        
  upload-portal-data-to-sit-env:
    needs: [ download-portal-data-from-build-env ]
    runs-on:  ubuntu-latest
    environment: sit
    env:
      RUNNER_DEBUG: 1
    steps:

    - uses: actions/checkout@v3
      with:
        lfs: true      

    - name: Fetch the ready to ship solution from GH artifact store
      uses: actions/download-artifact@v2
      with:
        name: build-portaldata
        path: portaldata/rdm-electrical-contractors-portal

    - name: Display List of Directories
      run: |
          ls -d */
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: upload-paportal
      uses: microsoft/powerplatform-actions/upload-paportal@v0
      with:
        environment-url: ${{ secrets.sit_url }}
        app-id: ${{ secrets.sit_client_id }}
        client-secret: ${{ secrets.sit_secrets_id }}
        tenant-id: ${{ secrets.sit_tenant_id }}
        upload-path: portaldata/${{ inputs.portal_name }}
