name: eql_cmx_reference_data_migration_to_sit.yaml

on:
  workflow_call :

    secrets:
      build_url:
        description: 'reference_data environment url.'
        required: true      
      build_client_id:
        description: 'The reference_data client id'
        required: true
      build_secrets_id:
        description: 'The secret value for authentication for reference_data'
        required: true
      build_tenant_id:
        description: 'The tenant id'
        required: true
      sit_url:
        description: 'reference_data environment url.'
        required: true      
      sit_client_id:
        description: 'The reference_data client id'
        required: true
      sit_secrets_id:
        description: 'The secret value for authentication for reference_data'
        required: true
      sit_tenant_id: 
        description: 'The tenant id'
        required: true        

jobs:
  download-reference-data-from-build-env:
    runs-on:  windows-latest
    environment: build
    env:
      RUNNER_DEBUG: 1
    steps:

    - uses: actions/checkout@v3
      with:
        lfs: true
        
    - name: export-data
      uses: microsoft/powerplatform-actions/export-data@v0
      with:
        environment-url: ${{ secrets.build_url }}
        app-id: ${{ secrets.build_client_id }}
        client-secret: ${{ secrets.build_secrets_id }}
        tenant-id: ${{ secrets.build_tenant_id }}
        schema-file: schema-file/rdm-reference-data.xml
        data-file: referencedata
        overwrite: true

    - name: Upload the ready to ship reference-data to GH artifact store
      uses: actions/upload-artifact@v2
      with:
        name: build-referencedata
        path: referencedata
        
  upload-reference-data-to-sit-env:
    needs: [ download-reference-data-from-build-env ]
    runs-on:  windows-latest
    environment: sit
    env:
      RUNNER_DEBUG: 1
    steps:

    - uses: actions/checkout@v3
      with:
        lfs: true      

    - name: Fetch the ready to ship solution from GH artifact store
      uses: actions/download-artifact@v2
      with:
        name: build-referencedata
        path: referencedata
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: import-data
      uses: microsoft/powerplatform-actions/import-data@v0
      with:
        environment-url: ${{ secrets.sit_url }}
        app-id: ${{ secrets.sit_client_id }}
        client-secret: ${{ secrets.sit_secrets_id }}
        tenant-id: ${{ secrets.sit_tenant_id }}
        data-file: referencedata
