name: eql_cmx_reference_data_import_to_dev.yaml

run-name: Triggered by @${{ github.actor }}

on:
  workflow_call :
    secrets:
      dev_url:
        description: 'reference_data environment url.'
        required: true      
      dev_client_id:
        description: 'The reference_data client id'
        required: true
      dev_secrets_id:
        description: 'The secret value for authentication for reference_data'
        required: true
      dev_tenant_id:
        description: 'The tenant id'
        required: true

jobs:

  upload-reference-data-to-build-env:
    runs-on:  windows-latest
    environment: dev
    env:
      RUNNER_DEBUG: 1
    steps:

    - uses: actions/checkout@v3
      with:
        lfs: true
        ref: develop
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}


    - name: import-data
      uses: microsoft/powerplatform-actions/import-data@v0
      with:
        environment-url: ${{ secrets.dev_url }}
        app-id: ${{ secrets.dev_client_id }}
        client-secret: ${{ secrets.dev_secrets_id }}
        tenant-id: ${{ secrets.dev_tenant_id }}
        data-file: referencedata
