name: eql_cmx_reference_data_import_to_sit.yaml

on:
  workflow_call :

    secrets:
      sit_url:
        description: 'reference_data environment url.'
        required: true      
      sit_client_id:
        description: 'The reference_data client id'
        required: true
      sit_secrets_id:
        description: 'The secret value for authentication for reference_data'
        required: true
      sit_tenant_id: 
        description: 'The tenant id'
        required: true        

jobs:
  upload-reference-data-to-sit-env:
    runs-on:  windows-latest
    environment: sit
    env:
      RUNNER_DEBUG: 1
    steps:

    - uses: actions/checkout@v3
      with:
        lfs: true
        ref: develop
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: import-data
      uses: microsoft/powerplatform-actions/import-data@v0
      with:
        environment-url: ${{ secrets.sit_url }}
        app-id: ${{ secrets.sit_client_id }}
        client-secret: ${{ secrets.sit_secrets_id }}
        tenant-id: ${{ secrets.sit_tenant_id }}
        data-file: referencedata/data
